// <auto-generated />
using System;
using Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace hkd.ms.gestaoUsuario.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Api.Data.Models.Golpe", b =>
                {
                    b.Property<int>("IdGolpe")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descricao");

                    b.Property<int?>("MidiaLongaId");

                    b.Property<int?>("MidiauCurtaId");

                    b.Property<string>("Nome");

                    b.HasKey("IdGolpe");

                    b.HasIndex("MidiaLongaId");

                    b.HasIndex("MidiauCurtaId");

                    b.ToTable("Golpes");
                });

            modelBuilder.Entity("Api.Data.Models.Midia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Name");

                    b.Property<int>("Tipo");

                    b.HasKey("Id");

                    b.ToTable("Midias");
                });

            modelBuilder.Entity("Api.Data.Models.Golpe", b =>
                {
                    b.HasOne("Api.Data.Models.Midia", "MidiaLonga")
                        .WithMany()
                        .HasForeignKey("MidiaLongaId");

                    b.HasOne("Api.Data.Models.Midia", "MidiauCurta")
                        .WithMany()
                        .HasForeignKey("MidiauCurtaId");
                });
#pragma warning restore 612, 618
        }
    }
}
